"""Probe rebase-grid data availability and (re)generate the grid zone registry.

For every European zone (list mirrors rebase-grid's config/zones/*.yaml) and
every grid problem variable, three windows are probed against the API:

* fresh      — a full day shortly before the problem DATA_END pin; the series
               must exist and (for wind/solar) peak above a dead-fuel floor.
* guard-min  — 6h at DATA_END minus ~9 months; enough history for the problem
               family's minimum-training guard.
* full-depth — 6h at DATA_END minus ~2 years; marks zones with complete
               backfill for the full HISTORY window.

A (zone, variable) pair qualifies (becomes an emflow problem variant) when
fresh and guard-min both pass. Output is written to
``emflow/benchmarks/grid/zones.py``.

Usage::

    EMFLOW_GRID_API_KEY=... python scripts/probe_grid_zones.py [--dry-run]
"""

from __future__ import annotations

import argparse
import os
import sys
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
import requests

BASE_URL = os.environ.get("EMFLOW_GRID_BASE_URL", "https://grid.rebase.energy/api")
OUT_PATH = Path(__file__).resolve().parents[1] / "emflow" / "benchmarks" / "grid" / "zones.py"

# European zones served by rebase-grid (source: rebase-grid config/zones/*.yaml).
EUROPEAN_ZONES = [
    "AL", "AT", "BA", "BE", "BG", "CH", "CZ", "DE-LU", "DK-BHM", "DK-DK1",
    "DK-DK2", "EE", "ES", "FI", "FR", "GB", "GB-NIR", "GR", "HR", "HU", "IE",
    "IT-CAL", "IT-CNO", "IT-CSO", "IT-NO", "IT-SAR", "IT-SIC", "IT-SO", "LT",
    "LV", "MD", "ME", "MK", "NL", "NO-NO1", "NO-NO2", "NO-NO3", "NO-NO4",
    "NO-NO5", "PL", "PT", "RO", "RS", "SE-SE1", "SE-SE2", "SE-SE3", "SE-SE4",
    "SI", "SK", "UA", "XK",
]

VARIABLES = {
    "demand": ("consumption", {}, 0.0),   # endpoint, params, dead-fuel floor (MW)
    "wind": ("production", {"fuel": "wind"}, 5.0),
    "solar": ("production", {"fuel": "solar"}, 5.0),
}


def _series_max(key: str, zone: str, variable: str, start: str, end: str) -> float | None:
    """Max non-null value over the window, or None when no data."""
    import time

    endpoint, params, _ = VARIABLES[variable]
    data = None
    for attempt in range(5):
        try:
            resp = requests.get(
                f"{BASE_URL}/v1/zone/{zone}/{endpoint}",
                params={"start": start, "end": end, "resolution": "1H", **params},
                headers={"X-API-Key": key}, timeout=60,
            )
        except requests.RequestException:
            time.sleep(2 ** attempt)
            continue
        if resp.status_code in (429, 502, 503, 504):
            time.sleep(int(resp.headers.get("Retry-After", 0)) or 2 ** attempt + 1)
            continue
        if resp.status_code != 200:
            return None
        data = resp.json().get("data") or {}
        break
    if data is None:
        return None
    values = [v for col, vals in data.items() if col != "datetime"
              for v in vals if v is not None]
    return max(values) if values else None


def probe(key: str, data_end: pd.Timestamp) -> dict:
    fresh_start = data_end - pd.Timedelta(days=7)
    windows = {
        "fresh": (fresh_start, fresh_start + pd.Timedelta(days=1)),
        "guard": (data_end - pd.Timedelta(days=270), None),
        "depth": (data_end - pd.Timedelta(days=725), None),
    }

    def check(zone, variable):
        _, _, floor = VARIABLES[variable]
        f0, f1 = windows["fresh"]
        peak = _series_max(key, zone, variable, f0.isoformat(), f1.isoformat())
        if peak is None or peak <= floor:
            return zone, variable, None
        tiers = {"fresh_peak_mw": round(peak, 1)}
        for tier in ("guard", "depth"):
            t0 = windows[tier][0]
            v = _series_max(key, zone, variable, t0.isoformat(),
                            (t0 + pd.Timedelta(hours=6)).isoformat())
            tiers[tier] = v is not None
        return zone, variable, tiers

    registry: dict[str, dict] = {}
    jobs = [(z, v) for z in EUROPEAN_ZONES for v in VARIABLES]
    with ThreadPoolExecutor(max_workers=3) as pool:
        for zone, variable, tiers in pool.map(lambda a: check(*a), jobs):
            if tiers is None or not tiers["guard"]:
                continue
            entry = registry.setdefault(zone, {"key": zone, "variables": {}})
            entry["variables"][variable] = {
                "full_depth": tiers["depth"],
                "fresh_peak_mw": tiers["fresh_peak_mw"],
            }
    return dict(sorted(registry.items()))


def render(registry: dict, data_end: pd.Timestamp) -> str:
    lines = [
        '"""Grid zone registry — GENERATED by scripts/probe_grid_zones.py.',
        "",
        "Zones and variables that pass the rebase-grid data-availability probe",
        f"(probed {datetime.now(timezone.utc):%Y-%m-%d} against DATA_END "
        f"{data_end.isoformat()}). A (zone, variable) entry means: fresh data",
        "near DATA_END and history at least ~9 months back; ``full_depth``",
        "flags complete ~2-year backfill. Regenerate rather than hand-edit.",
        '"""',
        "",
        "ZONE_REGISTRY = {",
    ]
    for zone, entry in registry.items():
        slug = zone.lower()
        lines.append(f"    {slug!r}: {{")
        lines.append(f"        \"key\": {zone!r},")
        lines.append("        \"variables\": {")
        for var, meta in sorted(entry["variables"].items()):
            lines.append(f"            {var!r}: {meta!r},")
        lines.append("        },")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    key = os.environ.get("EMFLOW_GRID_API_KEY") or os.environ.get("GRID_API_KEY")
    if not key:
        sys.exit("set EMFLOW_GRID_API_KEY (or GRID_API_KEY)")

    from emflow.benchmarks.grid.problem import DATA_END

    registry = probe(key, DATA_END)
    pairs = sum(len(e["variables"]) for e in registry.values())
    print(f"{len(registry)} zones, {pairs} qualifying (zone, variable) pairs")
    source = render(registry, DATA_END)
    if args.dry_run:
        print(source)
    else:
        OUT_PATH.write_text(source)
        print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
